"""Added toppings table

Revision ID: a7abb604ed89
Revises: c3f87ade5aee
Create Date: 2020-09-03 19:20:18.007688

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7abb604ed89"
down_revision = "c3f87ade5aee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "toppings",
        sa.Column("toppings_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("toppings_id", name=op.f("pk_toppings")),
    )
    op.add_column("items", sa.Column("toppings_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_items_toppings_id_toppings"),
        "items",
        "toppings",
        ["toppings_id"],
        ["toppings_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_items_toppings_id_toppings"), "items", type_="foreignkey"
    )
    op.drop_column("items", "toppings_id")
    op.drop_table("toppings")
    # ### end Alembic commands ###
