"""Orders and items

Revision ID: c3f87ade5aee
Revises: b2e313fdf231
Create Date: 2020-05-24 09:08:42.902968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3f87ade5aee"
down_revision = "b2e313fdf231"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("orders_id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=6), nullable=True),
        sa.PrimaryKeyConstraint("orders_id", name=op.f("pk_orders")),
        sa.UniqueConstraint("reference", name=op.f("uq_orders_reference")),
    )
    op.create_table(
        "items",
        sa.Column("items_id", sa.Integer(), nullable=False),
        sa.Column("orders_id", sa.Integer(), nullable=True),
        sa.Column("pizzas_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["orders_id"], ["orders.orders_id"], name=op.f("fk_items_orders_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["pizzas_id"], ["pizzas.pizzas_id"], name=op.f("fk_items_pizzas_id_pizzas")
        ),
        sa.PrimaryKeyConstraint("items_id", name=op.f("pk_items")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    op.drop_table("orders")
    # ### end Alembic commands ###
